name: Clean up old Docker images

on:
  workflow_dispatch:
    inputs:
      pkg:
        description: 'Package name'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old container image versions
        uses: actions/delete-package-versions@v5
        with:
          owner: technobureau
          package-name: ${{ github.event.inputs.pkg }}
          package-type: "container"
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
