name: Image Build

on:
  workflow_dispatch:
   inputs:
    image:
      description: 'Name of the Docker image to build'
      required: true
      default: 'snooze'
      type: string
env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_DEFAULT_PLATFORM: linux/amd64
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker Build
        id: images
        run: |
          builders/${{ github.event.inputs.image }}/build.sh
