name: container cleanup

on:
  schedule:
    - cron: "0 3 * * 0" # Every Sunday at 3 AM UTC
  workflow_dispatch:

jobs:
  list-and-clean:
    runs-on: ubuntu-latest
    env:
      ORG: technobureau
    steps:
      - name: Fetch all container packages
        id: packages
        run: |
          packages=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github+json" \
                          https://api.github.com/orgs/${ORG}/packages?package_type=container \
                    | jq -r '.[].name')
          echo "::set-output name=packages::$packages"

      - name: Delete old versions for each package
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pkgs = `${{ steps.packages.outputs.packages }}`.split(" ");
            for (const pkg of pkgs) {
              console.log(`Cleaning package: ${pkg}`);
              await github.rest.actions.createWorkflowDispatch({
                owner: process.env.ORG,
                repo: context.repo.repo,
                workflow_id: 'cleanup-package.yml',
                ref: context.ref,
                inputs: { pkg }
              });
            }
